[package]
name = "rustcat"
version = "3.0.1"
authors = ["robiot", "Kolya142"]
description = "The Modern Port Listener and Reverse Shell"
license = "GPL-3.0-only"
repository = "https://github.com/Kolya142/rustcat"
edition = "2021"

[[bin]]
name = "rcat"
path = "src/main.rs"

[dependencies]
clap = { version = "3.2.17", features = ["derive"] }
colored = "2.0.0"
rustyline = "10.0.0"
log = "0.4.17"
fern = { version = "0.6.1", features = ["colored"] }

[target.'cfg(unix)'.dependencies]
termios = "0.3"
signal-hook = "0.3.14"
